version: '3.8'
services: 
  jaeger-server:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "14268"
      - "14250"

  zipkin-server:
    image: openzipkin/zipkin:latest
    ports:
      - "9411:9411"
  
  imds:
    image: amazon/amazon-ec2-metadata-mock:v1.5.0
    command: --hostname 0.0.0.0
    ports:
      - "1338:1338"
      
  collector:
    # build:
    #  context: ../../../../opentelemetry-collector-contrib
    #  dockerfile: examples/tracing/Dockerfile
    image: otel/opentelemetry-collector-contrib-dev
    command: --config /config/collector-config.yaml --log-level DEBUG
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_REGION
    ports:
      - "55680:55680"
      - "55681:55681"
      - "14268"
    volumes:
      - ./collector-config.yaml:/config/collector-config.yaml
      - ~/.aws:/root/.aws
    depends_on:
      - zipkin-server
      - jaeger-server
